### PR TITLE
Bump to version 3.3.15 to fix four issues

### PR DESCRIPTION
**Pull request by HouzuoGuo**
* Correctly install sss name databases even in the presence of
    special NSS database directives (bsc#1024841).
  * Fix missing translation of "Leave Domain" button (bsc#1038291).
  * Do AD's DNS lookup in lower case (bsc#1038720).
  * Understand XML data exported by SLES 12 SP0 (bsc#1040393).

### CODE REVIEW

**Comment by HouzuoGuo** [comment]
@jreidinger @shundhammer this one is for you :1st_place_medal:

**Comment by HouzuoGuo** [comment]
@shundhammer please LGFM :smile:

**Comment by HouzuoGuo** [comment]
@shundhammer could you or anyone LGTM?

**Comment by jreidinger** [comment]
@HouzuoGuo approved

**Comment by HouzuoGuo** [comment]
ta

**Pull request merged**
