### PR TITLE
Relax-NG ... Some defines for timeout needs the combine attribute (merge)

### PR DESCRIPTION
**Pull request by mvidner**
Merge #45 to master, and mark the whole SLE-12-GA maintenance branch as merged; see today's merge commits for details.

### CODE REVIEW

**Comment by mvidner** [comment]
@HouzuoGuo can you please verify that I merged the previous commits correctly?

**Comment by jreidinger** [comment]
code wise LGTM

**Comment by HouzuoGuo** [comment]
Sorry I am not very familiar with the Autoyast implementation of auth-client module, @varkoly please check.

**Comment by mvidner** [comment]
@HouzuoGuo no, the AutoYaST bits have been checked by Josef. I meant the other part: this PR claims to merge many commits from SLE-12-GA to master, but in fact no diffs are merged. This is because
1. the same change was previously made to SLE and master, without merging: 1ad528e8bc81ee56344cc4c492f5bc5c1cc8a8d3 and 293068f873dddd5b17a88faca7e1b9f01dbcce10
2. the change is unnecessary because master has changed so much that the bug is fixed in a different way, as you said in https://bugzilla.suse.com/show_bug.cgi?id=931515#c25

So I wanted to ask you to double-check whether my reasoning and git bits are correct.

**Comment by HouzuoGuo** [comment]
Aha! Now I see.

All commits are looking good!

**Comment by mvidner** [comment]
Thank you!

**Pull request merged**
