### PR TITLE
bnc#893983 - yast2-auth-client has hard requires for sssd

### PR DESCRIPTION
**Pull request by varkoly**

### CODE REVIEW

**Comment by jreidinger** [comment]
LGTM, just make it mergable

**Comment by varkoly** [comment]
I've also fixed:bnc# 907830 No option to 'Create Home Directory on Login' in Authentication module

**Comment by jreidinger** [comment]
I am slighly confused what is difference to https://github.com/yast/yast-auth-client/pull/28 as it mention same bug

**Comment by varkoly** [comment]
I've not fixed bnc#907830 for SLE12 only for master.
May be I'll do it also.

**Comment by mvidner** [comment]
@varkoly Péter, the IBS build has been failing with "error: %changelog not in descending chronological order"
http://river.suse.de/job/yast-auth-client-master/41/console

**Comment by varkoly** [comment]
@mvidner I can not see the problem: The diff of changelog in
https://github.com/yast/yast-auth-client/pull/28/files seems to be OK.

Am Dienstag, den 20.01.2015, 02:17 -0800 schrieb Martin Vidner:
> @varkoly Péter, the IBS build has been failing with "error: %changelog
> not in descending chronological order"
> http://river.suse.de/job/yast-auth-client-master/41/console
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> 

-- 
Peter Varkoly
Sr. Developer SUSE Linux Enterprise Applications
SUSE LINUX Products GmbH,
GF: Jeff Hawn, Jennifer Guild, Felix Imendörffer, HRB 16746 (AG
Nürnberg)
Maxfeldstraße 5
90409 Nürnberg
Germany

**Comment by mvidner** [comment]
@varkoly Sure, the `SLE-12-GA` branch is fine. I am talking about `master`.

**Pull request merged**
